# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistant_user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.general_frame = QtWidgets.QFrame(self.centralwidget)
        self.general_frame.setGeometry(QtCore.QRect(10, 10, 370, 420))
        self.general_frame.setMinimumSize(QtCore.QSize(370, 420))
        self.general_frame.setMaximumSize(QtCore.QSize(370, 420))
        self.general_frame.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(142, 120, 170);\n"
"border: 3px solid black;\n"
"")
        self.general_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.general_frame.setObjectName("general_frame")
        self.tBtn_closeWindow = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_closeWindow.setGeometry(QtCore.QRect(310, 10, 45, 30))
        self.tBtn_closeWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_closeWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tBtn_closeWindow.setFont(font)
        self.tBtn_closeWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_closeWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_closeWindow.setObjectName("tBtn_closeWindow")
        self.tBtn_minimaze = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_minimaze.setGeometry(QtCore.QRect(260, 10, 45, 30))
        self.tBtn_minimaze.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_minimaze.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_minimaze.setFont(font)
        self.tBtn_minimaze.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_minimaze.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_minimaze.setObjectName("tBtn_minimaze")
        self.tBtn_check_micro = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_check_micro.setGeometry(QtCore.QRect(10, 10, 195, 30))
        self.tBtn_check_micro.setMinimumSize(QtCore.QSize(195, 30))
        self.tBtn_check_micro.setMaximumSize(QtCore.QSize(195, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_check_micro.setFont(font)
        self.tBtn_check_micro.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_check_micro.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_check_micro.setObjectName("tBtn_check_micro")
        self.tBtn_start_speaking = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_start_speaking.setGeometry(QtCore.QRect(10, 350, 350, 50))
        self.tBtn_start_speaking.setMinimumSize(QtCore.QSize(350, 50))
        self.tBtn_start_speaking.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_start_speaking.setFont(font)
        self.tBtn_start_speaking.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_start_speaking.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_start_speaking.setObjectName("tBtn_start_speaking")
        self.output_text_information = QtWidgets.QPlainTextEdit(self.general_frame)
        self.output_text_information.setGeometry(QtCore.QRect(10, 55, 350, 280))
        self.output_text_information.setMinimumSize(QtCore.QSize(350, 280))
        self.output_text_information.setMaximumSize(QtCore.QSize(350, 280))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.output_text_information.setFont(font)
        self.output_text_information.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.output_text_information.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(142, 120, 170);\n"
"border: 3px solid black;\n"
"color: white;\n"
"")
        self.output_text_information.setReadOnly(True)
        self.output_text_information.setPlainText("")
        self.output_text_information.setObjectName("output_text_information")
        self.tBtn_commands = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_commands.setGeometry(QtCore.QRect(210, 10, 45, 30))
        self.tBtn_commands.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_commands.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_commands.setFont(font)
        self.tBtn_commands.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_commands.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_commands.setObjectName("tBtn_commands")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Голосовой ассистент"))
        self.tBtn_closeWindow.setText(_translate("MainWindow", "X"))
        self.tBtn_minimaze.setText(_translate("MainWindow", "_"))
        self.tBtn_check_micro.setText(_translate("MainWindow", "Проверить микрофон"))
        self.tBtn_start_speaking.setText(_translate("MainWindow", "Начать"))
        self.tBtn_commands.setText(_translate("MainWindow", "?"))
